import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Privacy Policy - APEX',
}

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-bg text-white">
      <nav className="border-b border-white/[0.04]">
        <div className="max-w-3xl mx-auto px-6 py-4">
          <Link href="/" className="font-bold text-lg">APEX</Link>
        </div>
      </nav>
      <div className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-3xl font-bold mb-8">Privacy Policy</h1>
        <div className="prose prose-invert prose-sm max-w-none space-y-6 text-white/60 leading-relaxed">
          <p><strong className="text-white">Last updated:</strong> March 2026</p>

          <h2 className="text-xl font-semibold text-white mt-8">1. Information We Collect</h2>
          <p>We collect your email address at signup. If you connect a Hyperliquid API key, it is stored encrypted (AES-256-GCM) in our database. We collect trading activity data generated by the bot for your dashboard.</p>

          <h2 className="text-xl font-semibold text-white mt-8">2. How We Use Your Data</h2>
          <p>Your data is used solely to provide the APEX service: executing trades, displaying your dashboard, and sending notifications you configure. We do not sell or share your data with third parties.</p>

          <h2 className="text-xl font-semibold text-white mt-8">3. Data Storage</h2>
          <p>Data is stored in Supabase (PostgreSQL) with row-level security. API keys are encrypted at rest. All connections use TLS encryption in transit.</p>

          <h2 className="text-xl font-semibold text-white mt-8">4. Third-Party Services</h2>
          <p>We use Stripe for payment processing, Supabase for authentication and database, and Hyperliquid for trade execution. Each has their own privacy policy.</p>

          <h2 className="text-xl font-semibold text-white mt-8">5. Data Deletion</h2>
          <p>You may request deletion of your account and all associated data at any time by contacting support@apexhl.trade. We will process deletion requests within 30 days.</p>

          <h2 className="text-xl font-semibold text-white mt-8">6. Cookies</h2>
          <p>We use essential cookies for authentication only. No tracking or advertising cookies are used.</p>

          <h2 className="text-xl font-semibold text-white mt-8">7. Contact</h2>
          <p>Privacy questions? Email us at support@apexhl.trade.</p>
        </div>
      </div>
    </div>
  )
}
